#!/bin/bash

#ma is short for module add variable
#I am basing it off of github commands git add but only using the first letter of each word
#add a help message here

scriptName="mod add"
function printUsage () {
    cat <<EOF

Synopsis

    $scriptName [-h | --help] <modulename> <VariableNAME> <Filename>

Description:
	modulename: 	is the current module but does not include the version
	VariableNAME:	is the variable you want to add to the module file
	FileName:       is the name of the file or text you wish you put into a variable

Author

    Andrew Severin, Genome Informatics Facilty, Iowa State University
    severin@iastate.edu
    1 December, 2015


EOF
}
#need to have a check to see if the module already exists or rather the version of that module 
#add modtype variable in prepgenome modules and software modules so that we can distinguish between the two.
#for software modules it could prompt the user perhaps?
#perhaps nothing for software or modtyp=software 
#does software already exist? then copy important fields into new version
#generic variable to file
#genomic variable for text
#mod commit maybe fore the variable to text?
#mod add file is default?
#mod add text
#check to see if third input is a file then use that to do variable file vs text

if [ $# -lt 3 ] ; then
        printUsage
        exit 0
fi
numparamsM2=$(expr $# - 2)
MODULE=$1
VAR=$2
shift;shift
FILE=$@
PWD=$(pwd -P)

#my attempt to combine adding of directories and preexisting variables
#DIR=$(echo "${BASH_ARGV[*]}" | cut -d " " -f -$numparamsM2)
#echo $DIR
unset modulefile
module load $MODULE
#Here are some required variables
modulefile=$(module show $MODULE 2>&1 | head -n 2 | tail -n 1| perl -pe 's/://')
BUILD=$(basename $modulefile)
moduledir=$(dirname $modulefile)
modulename=$(basename $moduledir)
#echo $modulefile
#echo $VERSION
#echo $moduledir
#if modtype = genome
BUILD2=$(echo ${BUILD//./p})

#remove periods and dashes that setenv will error on
VAR=$(echo $VAR | perl -pe 's/[-\.]/_/g')

#check to see if it is a file
if [ -f "$FILE" | [ -d "$FILE" ]
then
cat << MODFILE >> $modulefile
setenv	${modulename}_${BUILD2}_${VAR}	$PWD/${FILE}
MODFILE

echo -e 'setenv\t'${modulename}_${BUILD}_${VAR}'\t'$PWD'/'$FILE'\t\t :was added to '$MODULE''
else
#if it is not a file then add the environmental variable as text
cat << MODFILE >> $modulefile
setenv  ${modulename}_${BUILD2}_${VAR}       "${FILE}"
MODFILE
echo  -e 'setenv\t'$modulename'_'$BUILD'_'$VAR'\t'$FILE'\t\t :was added to '$MODULE''
fi

#then
#echo -e 'setenv\t"'$MODULE'"_"'$BUILD'"_"'$VAR'"\t"'$PWD'/'$FILE'"' >> $modulefile
#echo -e 'setenv\t'$MODULE'_'$BUILD'_'$VAR'\t'$PWD'/'$FILE'\t\t :was added to '$MODULE''
#else
#echo  -e 'setenv\t"'$MODULE'"_"'$BUILD'"_"'$VAR'"\t"'$FILE'"' >> $modulefile
#echo  -e 'setenv\t'$MODULE'_'$BUILD'_'$VAR'\t'$FILE'\t\t :was added to '$MODULE''




module load $MODULE
